### ISSUE TITLE
Enforce naming standard in -c course name option

### ISSUE THREAD

**Issue by MarkBaggett** [sans-sroc/integrity#33]
The media processor must have a way of identifying which course it is processing.   If the version file contains an ambiguous course name then I am unable to process it.   I generate an error message, but since it is a back end process it would be better to catch this when the instructor runs integrity and have them enter a valid course name at that time.   As long as it is VERSION-[A-Z]{3}\d{3}"   I will be able to process it.  You may or may not want to be more specific. 

Example unacceptable names;
VERSION-573-21-1
VERSION-511.21.1

Example acceptable names:
VERSION-SEC573-21-1
VERSION-SEC573_G01_02

**Comment by ekristen** [comment]
@philhagen @mark-hallman I believe this is your territory. Can we enforce it this format or will that cause problems?

**Comment by mark-hallman** [comment]
Like we all have time, but this probably may need a real-time discussion. 

Courseware has dropped the three-letter curriculum identifier in some instances and uses it in others.  So that begs the question,  ["What](url) is an acceptable course name"?   What does Mark need for processing and what is courseware expecting.  Look at the screen-shot below to see how the three-letter course ID is being dropped.

![image](https://user-images.githubusercontent.com/16808320/117676965-0ac9f200-b17c-11eb-9b0e-0caebcd0dd7f.png)

**Comment by ekristen** [comment]
@MarkBaggett are you using the JSON output? If so we could alter it to include more rich information like courseware information. It only shows files information at this point, but we could also add a roll up field like `validates` true/false for overall knowing if it was successful or not.

**Comment by philhagen** [comment]
This may become a non-issue due to #36.  Standby before worrying too much more on this one.
